const serviceUrl= 'http://192.168.10.100';

//const serviceUrl= 'https://panda36.com';
//const serviceUrl= 'http://test.baixingliangfan.cn/baixing/';
const servicePath={
  'Shop-Index-index':'/m/index/index',
  'Shop-Shop-getGoodsInfo': '/m/shop/goods',
  'Shop-Index-getUserInfo': '/m/index/getuserinfo',
  'Shop-register-register': '/m/register/register',
  'Shop-Shop-goodsList': '/m/shop/goodslist',
  'Shop-Shop-getRecommend': '/m/shop/getrecommend',
  'Shop-Shop-getComment': '/m/shop/getcomment',
  'Shop-cart-join': '/m/cart/join',
  'Shop-Login-login': '/m/login/login',
  'Shop-Login-logout': '/m/login/logout',
  'Shop-Shopping_cart-remove': '/m/cart/remove',
  'Shop-Shopping_cart-index': '/m/cart/index',
  'Shop-Shopping_cart-changeGoodsNumber': '/m/cart/changegoodsnumber',
  'Shop-Shopping_cart-selectOneShoppingCartGoods': '/m/cart/selectoneshoppingcartgoods',
  'Shop-Shopping_cart-selectAllShoppingCartGoods': '/m/cart/selectallshoppingcartgoods',
  'Shop-Shopping_step-step1': '/m/step/step1',
  'Shop-Shopping_step-step2': '/m/step/step2',
  'Shop-Shopping_step-step3': '/m/step/step3',
  'Shop-Shopping_step-getConsignee': '/m/step/getconsignee',
  'Shop-Shopping_step-getFreight': '/m/step/getfreight',
  'Shop-Lostpwd-send': '/m/lostpwd/send',
  'Shop-Shop-search': '/m/shop/search',
  'Shop-Index-setlanguage': '/Shop/setlanguage',
  'Shop-Index-category':'/m/index/category',
  'Shop-Shop-getAttr':'/m/shop/getattr',
  'Shop-step-getvoucherlist': '/Shop/step/getvoucherlist',
  'Shop-Index-actlist': '/m/index/actlist',
  'Shop-Shoppingcart-index': '/m/cart/index',
  'payway-voucher-index.php?u=/Pay': 'payway/voucher/index.php?u=/Pay',
  'Shop-Snap_up-seriesSnapUp':'/m/snap_up/series_snap_up',
  'Shop-Snap_up-goodsList':'/m/snap_up/goodslist',
  'Shop-Snap_up-times':'/m/snap_up/times',
  'Shop-Index-actList': '/m/index/actlist',
  'payway-Voucher-index.php?u=/Pay': 'payway/voucher/index.php?u=/Pay',

  //u模块
  "User-User-recommend1": "/u/user/recommend1",
  'User-consignee-edit': '/u/consignee/edit',
  'User-consignee-add': '/u/consignee/add',
  'User-money-index':'/u/money/index',
  'User-consignee-default':'/u/consignee/default',
  'User-Profile-index':'/u/profile/index',
  'User-consignee-list':'/u/consignee/list',
  'User-profile-profile':'/u/profile/profile',
  'User-Consignee-del':'/u/consignee/del',
  'User-Order-deliveryConfirm':'/u/order/deliveryConfirm',
  'User-Order-getcomment':'/u/order/getcomment',
  'User-Order-comment':'/u/order/comment',
  'User-uploader-upload':'/u/uploader/upload',
  'User-profile-changepassword':'/u/profile/changepassword',
  'User-profile-changesecuritypassword':'/u/profile/changesecuritypassword',
  'User-User-issignin': '/u/user/issignin',
  'User-User-usersignin': '/u/user/usersignin'
};

